version: '3.8'

services:
  easemob-callback:
    build: .
    ports:
      - "9999:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EASEMOB_SECRET=${EASEMOB_SECRET}
      - LOG_LEVEL=info
      - CORS_ORIGIN=*
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
